apiVersion: apps/v1
kind: Deployment
metadata:
  name: knowledge-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knowledge
  template:
    metadata:
      labels:
        app: knowledge
    spec:
      containers:
        - name: knowledge
          image: logosapidev/logos_knowledge_api:latest
          env:
            - name: LOGOS_DB_URL
              valueFrom:
                secretKeyRef:
                  name: logosdb
                  key: LOGOS_DB_URL
            - name: LOGOS_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: logosdb
                  key: LOGOS_DB_USERNAME
            - name: LOGOS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: logosdb
                  key: LOGOS_DB_PASSWORD
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: JWT_SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: knowledge-srv
spec:
  selector:
    app: knowledge
  ports:
    - nodePort: 30949
      protocol: TCP
      port: 8083
      targetPort: 8083
  type: LoadBalancer
