apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rating
  template:
    metadata:
      labels:
        app: rating
    spec:
      containers:
        - name: rating
          image: logosapidev/logos_rating_api:latest
          env:
            - name: LOGOS_DB_URL
              valueFrom:
                secretKeyRef:
                  name: logosdb
                  key: LOGOS_DB_URL
            - name: LOGOS_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: logosdb
                  key: LOGOS_DB_USERNAME
            - name: LOGOS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: logosdb
                  key: LOGOS_DB_PASSWORD
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: JWT_SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: rating-srv
spec:
  selector:
    app: rating
  ports:
    - nodePort: 30952
      protocol: TCP
      port: 8086
      targetPort: 8086
  type: LoadBalancer
